[bot]
token = "6036683898:AAFRLNPNKYOPBV1QBtnM2ykEIzXINBfKYjk"

[database]
datetime_format = "%Y-%m-%d %H:%M"

[files]
how_to_send_geopos_screenshots = [
    "AgACAgIAAxkBAAICV2TI51VeaB0kOOY_3LaFLSE4rYiNAALHxjEbLs0ISpQQJox8dz7FAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAICVWTI51VebcxoDT1qFftoMBOUrEGeAALFxjEbLs0ISiB-4r-uVbV8AQADAgADeQADLwQ",
    "AgACAgIAAxkBAAICVmTI51WlHW7r1LO4gi4uYRfN1VULAALGxjEbLs0ISue4y3RNpZpSAQADAgADeQADLwQ"
]
wait_sticker = "CAACAgIAAxkBAAIDM2TMA7RyqtTEVZ_7whyRRcz-cBEaAAIjAAMoD2oUJ1El54wgpAYvBA"

[admin_chat]
id = -1001897868350

[admin_chat.threads]
backup = 317

[constants]
days = [
    "Понедельник",
    "Вторник",
    "Среда",
    "Четверг",
    "Пятница",
    "Суббота",
    "Воскресенье"
]
months = [
    "января",
    "февраля",
    "марта",
    "апреля",
    "мая",
    "июня",
    "июля",
    "августа",
    "сентября",
    "октября",
    "ноября",
    "декабря"
]
