[bot]
token = "6036683898:AAFRLNPNKYOPBV1QBtnM2ykEIzXINBfKYjk"
username = "test1234523432_bot"

[payments]
yookassa_token = "test_5uJtCYfPtF0vJtoIj6xuWCwvR3YflyEIjz5iym81jgc"
yookassa_shop_id = 250335
offer_url = "https://dpaste.org/d0wMB"

[database]
datetime_format = "%d.%m.%Y %H:%M"
date_format = "%d.%m.%Y"
time_format = "%H:%M"

[files]
how_to_send_geopos_screenshots = [
    "AgACAgIAAxkBAAICVWTI51VebcxoDT1qFftoMBOUrEGeAALFxjEbLs0ISiB-4r-uVbV8AQADAgADeQADLwQ",
    "AgACAgIAAxkBAAICVmTI51WlHW7r1LO4gi4uYRfN1VULAALGxjEbLs0ISue4y3RNpZpSAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAICV2TI51VeaB0kOOY_3LaFLSE4rYiNAALHxjEbLs0ISpQQJox8dz7FAQADAgADeQADLwQ",
]
wait_sticker = "CAACAgIAAxkBAAIDM2TMA7RyqtTEVZ_7whyRRcz-cBEaAAIjAAMoD2oUJ1El54wgpAYvBA"
start_video = "BAACAgIAAxkBAAIG3GTtkQLLlzZoXXSmMa5RV_0cVD_7AAIQLgACTRq5SJaX7K2SIZmAMAQ"

[admin_chat]
id = -1001897868350

[admin_chat.threads]
backup = 317

[constants]
days = [
    "Понедельник",
    "Вторник",
    "Среда",
    "Четверг",
    "Пятница",
    "Суббота",
    "Воскресенье",
]
months = [
    "января",
    "февраля",
    "марта",
    "апреля",
    "мая",
    "июня",
    "июля",
    "августа",
    "сентября",
    "октября",
    "ноября",
    "декабря",
]
